### ISSUE TITLE
MacOS test broken

### ISSUE THREAD

**Issue by dzerbino** [dpryan79/libBigWig#15]
Hello,

it seems that differences in Mac break tests that otherwise work fine in Linux, I'm guessing due to the use of explicit MD5 checksums:

disorientation:libBigWig dzerbino$ make test
./test/test.py
Traceback (most recent call last):
  File "./test/test.py", line 14, in <module>
    assert(md5sum == "a15cbf0021f3e80d9ddfd9dbe78057cf")
AssertionError
make: *** [test] Error 1

Cheers,

Daniel

**Comment by dzerbino** [comment]
Update: these are text files. They are identical between Linux and MacOS, except the EOL characters.

**Comment by dpryan79** [comment]
Oops, I meant to fix this, thanks for the reminder!

**Comment by dpryan79** [comment]
Actually, this works on both Travis and the Mac sitting beside me. Perhaps there's some sort of locale setting or version difference?

**Comment by dzerbino** [comment]
Possibly:

disorientation:~ dzerbino$ locale: 
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=

**Comment by dzerbino** [comment]
OK I found the culprint: I have python 3 installed on my laptop.

Pull request coming up.

**Comment by dpryan79** [comment]
Well that's wild, thanks for the PR!
