### ISSUE TITLE
Slow loading a remote BigWig file

### ISSUE THREAD

**Issue by andrewyatz** [dpryan79/libBigWig#22]
Sorry I seem to be finding a lot of these today. Anyway same stub program as before expect I've switched to using a UCSC example [bigwig file hosted at genome.ucsc.edu](http://genome.ucsc.edu/goldenPath/help/examples/bigWigExample.bw). The following code took over 3 minutes to return:

```c
#include "bigWig.h"
#include <stdio.h>
#include <inttypes.h>
#include <stdlib.h>

int main(int argc, char *argv[]) {
    bigWigFile_t *fp = NULL;
    double *stats = NULL;
    
    char file[] = "http://genome.ucsc.edu/goldenPath/help/examples/bigWigExample.bw";
    char chrom[] = "chr21";
    int start = 33031597;
    int end = 34041570;
    int full = 1;
    int bins = 100;
    
    int buffer = 1<<17;
    
    if(bwInit(buffer) != 0) {
        fprintf(stderr, "Received an error in bwInit\n");
        return 1;
    }
    
    fp = bwOpen(file, NULL, "r");
    if(!fp) {
        fprintf(stderr, "An error occured while opening %s\n", file);
        return 1;
    }
    if(full) 
      stats = bwStatsFromFull(fp, chrom, start, end, bins, mean);
    else 
      stats = bwStats(fp, chrom, start, end, bins, mean);

    if(stats)
      free(stats);

    bwClose(fp);
    bwCleanup();
    return 0;
}
```

My Perl code had similar issues and the following Python code had the same issues

```python
#!/usr/bin/env python

import pyBigWig
bw = pyBigWig.open("http://genome.ucsc.edu/goldenPath/help/examples/bigWigExample.bw")
bw.stats('chr21', 33031597, 34041570, type="mean", nBins=100, exact=True)
```

Doing a sample of the C process in OSX showed that 100% of the CPU time is spent in `__select` from the system kernel and the next level up was `Curl_poll` so I think it's spending its time transferring.  I did some info dumps on the BigWig and this is what I got back

```
$ bigWigInfo http://genome.ucsc.edu/goldenPath/help/examples/bigWigExample.bw
version: 1
isCompressed: no
isSwapped: 0
primaryDataSize: 56,335,300
primaryIndexSize: 227,048
zoomLevels: 7
chromCount: 1
basesCovered: 35,926,161
mean: 40.862151
min: 0.000000
max: 100.000000
std: 22.968515
```

The only bit I think is odd here is that it's an uncompressed bigwig file. I also tried mucking around with the buffer size and set it to 8MB. That brought the total time spent down to 15 seconds so I'm guessing there's a problem/limitation with uncompressed BigWigs and streaming them across the wire.

**Comment by dpryan79** [comment]
Interesting observation. When I wrote this library I don't think I was able to find uncompressed files for testing. My suspicion is that that simply doesn't work.

**Comment by dpryan79** [comment]
Give the `fix20` branch a try with this example now. The handling of remote uncompressed files was rather silly previously (the performance was terrible due to requesting only 4-8 bytes at a time).

**Comment by andrewyatz** [comment]
That speeds it up massively. Great work! There are two odd things though I don't quite understand from my end:

1). When running the compiled C code that's in this issue against the UCSC file I get a wall clock time of ~7 seconds. When I do the same query and params through my XS API I can do the query in ~2 seconds. Not sure why at all.

2). There's another error that appears if you ask for the summary statistics rather than full statistics

```
query(9518,0x7fffc24da3c0) malloc: *** error for object 0x7fd4dd014a00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

The frees I have in the example code do check if the struct/array was defined so I'm not totally sure but it may be coming from your layer.

**Comment by dpryan79** [comment]
This and another bug (you would have found it next) are now fixed in the `fix20` branch. I guess it shows that I only used compressed files for testing.

**Comment by andrewyatz** [comment]
Just tried it and got the error:

```
query(11352,0x7fffc24da3c0) malloc: *** error for object 0x7f8255801a00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

I had a look at the commit logs with `git log HEAD^..HEAD` and got

```
commit 33d436beb6ef08e60d1858f77d2a80ef0f910e6c
Author: Devon Ryan <dpryan79@gmail.com>
Date:   Fri Mar 17 14:53:35 2017 +0100

    More fixes for uncompressed file handling.
```

Seems that matches the HEAD commit I found for fix20

**Comment by dpryan79** [comment]
Make sure you do a `make clean`.

**Comment by andrewyatz** [comment]
:+1: that's worked. Verified in C and in my Perl layer. Sorry for being dumb. 

Just as an aside. I'm still confused how my XS version performs nearly 3 times as fast as a C binary version with the same parameters. No idea why. Anyway it all looks good now. Thank you!

**Comment by dpryan79** [comment]
Is your XS version a wrapper around this or is it using something else. This isn't exactly the most optimized code for remote file access, so if whatever else you're using is doing much of anything clever then that'll account for the difference.

Anyway, I'll merge this in and post a new release.

**Comment by andrewyatz** [comment]
It's a thin wrapper around your routines. You can see the main bit of the
library here
https://github.com/Ensembl/Bio-DB-Big/blob/master/lib/Bio/DB/Big.xs. The
routine is called `bf_get_stats`.

Thanks for the new release though.
