### ISSUE TITLE
Question: is it possible to merge bigwig files?

### ISSUE THREAD

**Issue by romgrk** [dpryan79/libBigWig#34]
Hey, I'm trying to write a CLI tool to merge to bigWig files. Is it something that is possible with this library? If so, would you be able to provide a basic example?
Otherwise, do you know where I can find a formal definition of the `.bigWig` format?

**Comment by dpryan79** [comment]
I don't have any specific merge functions in libBigWig, you would iterate over the intervals in two or more files and merge them as you go.

**Comment by romgrk** [comment]
So overall, I'd need to get the list of chroms for both files, merge them, iterate all intervals with `bwOverlappingIntervalsIterator`, and merge those intervals? And how would I merge those intervals?

Sorry for bothering, I'm a noob in regards to genomics data so I'm not even sure what those intervals represent :/

**Comment by cmdcolin** [comment]
You might look into https://github.com/Ensembl/WiggleTools

**Comment by romgrk** [comment]
Thanks @cmdcolin! But I went a different way, I forked kent tools and re-used the code of `bigWigMerge` to create `bigWigMergePlus`: a tool to directly merge bigWig files into another bigWig. It contains also a few more features that were needed in the case of our project, such as outputting the standard deviation. Release is here: https://github.com/c3g/kent/releases/tag/bigWigMergePlus_2.0.0

**Comment by nsheff** [comment]
FYI I think this is also basically what `bigWigCat` does

https://github.com/ENCODE-DCC/kentUtils/tree/master/src/utils/bigWigCat

**Comment by dpryan79** [comment]
I think `bigWigCat` is meant for when the intervals in the files don't overlap. I'd suggest sticking to wiggletools, which uses this library.
