### ISSUE TITLE
Support for extraIndex fields in BigBed files

### ISSUE THREAD

**Issue by andrewyatz** [dpryan79/libBigWig#48]
Hi there

We've started to use BigBed and libBigWig for a lot of our flat file reading and have started to use the extraIndex feature (see the kent source for [bigBedNamedItems](https://github.com/ucscGenomeBrowser/kent/blob/master/src/utils/bigBedNamedItems/bigBedNamedItems.c)). Currently we have to shell back out to run `bigBedNamedItems` to extract rows of the BigBed file we are interested in. Is there any possibility of supporting the extra indexes? It looks from https://github.com/ucscGenomeBrowser/kent/blob/master/src/lib/bigBed.c#L635 they're accessible from the file but also they require some AutoSQL parsing to process.

Anyway a general idea of how plausible support for these are would be really appreciated. Even if it's a case of no way.

Thanks

**Comment by dpryan79** [comment]
I can't say I'm terribly likely to implement autosql parsing in the base C library. I could maybe add that to the python wrapper (pyBigWig), but it's hard to get excited about parsing text in C.

**Comment by andrewyatz** [comment]
Not excited at building a C text parser in C. Cannot imagine why at all. This is a fair point though. What I'm not sure about yet is how intertwined the two systems are to each other.

If it would be a help I wrote a library for parsing AutoSQL using regular expressions in https://github.com/Ensembl/Bio-DB-Big/blob/master/lib/Bio/DB/Big/AutoSQL.pm#L54. It's in Perl but it seemed to handle the cases I could throw at it. Not sure how to construct regex in Python (also this feels wrong since a grammer should be able to handle this) but it might be a start

**Comment by andrewyatz** [comment]
https://github.com/ucscGenomeBrowser/kent/blob/master/src/hg/autoSql/autoSql.doc details the current grammar, which was used to create the regex parsing

**Comment by dpryan79** [comment]
After thinking about this a bit more I think I'll put this in the "I will happily accept PRs" category :)

**Comment by andrewyatz** [comment]
Awesome. Just need to figure out how then :)
