### ISSUE TITLE
Test failures on other architectures

### ISSUE THREAD

**Issue by mdb571** [dpryan79/libBigWig#61]
Hello there,

In Debian we run some of the tests you've included in `test/` as autopkgtest for [libbigwig](https://tracker.debian.org/pkg/libbigwig) package.
This is how we are running the tests in Debian
```
echo "1c52065211fdc44eea45751a9cbfffe0 test/Local.bw" >> checksums
echo "8e116bd114ffd2eb625011d451329c03 test/Write.bw" >> checksums
echo "ef104f198c6ce8310acc149d0377fc16 test/example_output.bw" >> checksums

LIB_STATIC=`find /usr/lib -name libBigWig.a`

#Compile using installed libbigwig
echo 'Compiling ...'
gcc -g -Wall   test/testLocal.c ${LIB_STATIC} -lBigWig -lcurl -lm -lz -o testlocal
gcc -g -Wall   test/testWrite.c ${LIB_STATIC} -lBigWig -lm -lz -lcurl -o testWrite
gcc -g -Wall   test/exampleWrite.c ${LIB_STATIC} -lBigWig -lcurl -lm -lz -o examplewrite

echo '------------------------------'

echo -e "Test 1"
./testlocal test/test.bw > test/Local.bw

echo -e "Test 2"
./testWrite test/test.bw test/Write.bw

echo -e "Test 3"
./examplewrite

md5sum --check checksums
echo -e "PASS"
```

Currently the tests are failing for i386 and s390 architectures.

The errors that we are getting are as follows

i386:

```
Compiling ...
------------------------------
Test 1
Test 2
Test 3
test/Local.bw: FAILED
test/Write.bw: FAILED
test/example_output.bw: OK
md5sum: WARNING: 2 computed checksums did NOT match
```
The output files generated have different hashsum. Is this expected ?

s390 (Big Endian) :

```
Compiling ...
------------------------------
Test 1
testlocal: test/testLocal.c:107: main: Assertion `bwIsBigWig(argv[1], NULL) == 1' failed.
/tmp/autopkgtest-lxc.y_h72gqc/downtmp/build.e6I/src/debian/tests/run-unit-test: line 32:  1996 Aborted                 ./testlocal test/test.bw > test/Local.bw
```

It would be helpful if you could help in debugging these failures :)

Thanks

**Comment by dpryan79** [comment]
I wouldn't be surprised if something breaks on s390, since the endian assumptions that I coded in will be different there. There's no reason to use this on an s390 (are any still actually used?). Since i386 was a 32-bit system I imagine the hashes will differ slightly. There's also no reason to use such an antiquated architecture anymore.

**Comment by mdb571** [comment]
Thanks for your insights on this. The best bet might be to disable the tests for these architectures in Debian. I just wanted to know your feedback if they're was possible fix for this. I'll go ahead and disable them. 

Closing this issue
